export default {
    init(folder, fs, os, path) {
        const gitignoreContent = [
            "# See http://help.github.com/ignore-files/ for more about ignoring files.",
            "",
            "/dist",
            "/docs/output",
            "/examples",
            "/tmp",
            "",
            "# dependencies",
            "/node_modules",
            "",
            "# generated by the theme-build",
            "/resources/theme-map.json",
            "",
            "# IDEs and editors",
            "/.idea",
            ".project",
            ".classpath",
            "*.launch",
            ".settings",
            ".vscode/",
            "",
            "#System Files",
            ".DS_Store",
            "Thumbs.db",
            "",
            "# Local AI Knowledge Base",
            ".env",
            "chroma-neo-knowledge-base/",
            "chroma-neo-memory-core/",
            "",
            "# Playwright test results",
            "test/playwright/test-results/",
            "# Single-file Playwright runs via npx",
            "test-results/",
        ].join(os.EOL);

        fs.writeFileSync(path.join(folder, '.gitignore'), gitignoreContent);
    }
};
