export default {
    init(folder, fs, os, path) {
        const gitignoreContent = [
            "# See http://help.github.com/ignore-files/ for more about ignoring files.",
            "",
            "package-lock.json",
            "",
            "/dist",
            "/docs/output",
            "/examples",
            "",
            "# dependencies",
            "/node_modules",
            "",
            "# generated by the theme-build",
            "/resources/theme-map.json",
            "",
            "# IDEs and editors",
            "/.idea",
            ".project",
            ".classpath",
            "*.launch",
            ".settings",
            ".vscode/",
            "",
            "#System Files",
            ".DS_Store",
            "Thumbs.db"
        ].join(os.EOL);

        fs.writeFileSync(path.join(folder, '.gitignore'), gitignoreContent);
    }
};
